org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=false
android.useAndroidX=true
# 项目路径含中文（手机小程序开发），AGP 默认拒绝非 ASCII 路径，需显式放行
android.overridePathCheck=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.nonFinalResIds=false
kotlin.code.style=official
